services:
  bb-app:
    build: .
    container_name: staging-bb-app
    restart: unless-stopped
    env_file: .env
    environment:
      PORT: "3001"
      DB_PATH: /data/beigeBoard.db
      STATIC_DIR: /app/dist
    volumes:
      - ${BEIGEBOARD_DATA_PATH:-/mnt/Luna/Backends-Staging/BeigeBoard-Data}:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bb-net
      - nginx-staging-proxy
networks:
  bb-net:
    name: staging-bb-net
  nginx-staging-proxy:
    external: true
    name: nginx-staging-proxy
